# Generated by Django 4.0.4 on 2022-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='manual_mode',
            field=models.BooleanField(default=False),
        ),
    ]
